apiVersion: apps/v1
kind: Deployment
metadata:
  name: koajs-deployment
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: koajs
        image: evgeny1307/koajs:v1.3
        ports:
        - containerPort: 5000